# docker-compose.yml
version: "3.5"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/db
      HOST: 0.0.0.0
      NODE_ENV: development
    ports:
      - "8000:8000"
    command: yarn run dev
    volumes:
      - .:/app/
      - /app/node_modules

  postgres:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
